### ISSUE TITLE
moveit_ros_warehouse failing 

### ISSUE THREAD

**Issue by davetcoleman** [davetcoleman/moveit#4]
i think i have the wrong branches being pulled in - probably should switch to 100% kinetic

**Comment by orajput** [comment]
First of all, thanks for the merged Moveit repos and the merge scripts. It has been really useful.

I have been able to successfully compile Moveit in ROS Kinetic (Ubuntu 16.04) by using the latest branches and your latest forks. My merged Moveit repo is: https://github.com/orajput/moveit

Following are details of the branches used for each moveit repo:
Repo                                | Latest Branch
----------------------------------- | --------------------------------------------------
core                                | kinetic-devel-synced (davetcoleman)
ros                                 | cbrew_warehouse_ros_refactor-fixed2 (davetcoleman)
planners                            | kinetic-devel-cpp11 (davetcoleman)
plugins                             | jade-devel
setup_assistant                     | jade-devel
commander                           | jade-devel
ikfast                              | kinetic-devel
resources                           | master
experimental                        | master
docs                                | kinetic-devel
msgs                                | jade-devel
srdfdom                             | indigo-devel
warehouse_ros                       | jade-devel
manipulation_msgs                   | hydro-devel
household_objects_database_msgs     | hydro-devel

**Comment by davetcoleman** [comment]
Great! Remember that this is still experimental. 

Can you create a PR with this table into the main README, merging it with the current table I have there?

**Comment by orajput** [comment]
I have created the [PR]() to add branches that can be used to successfully compile Moveit in ROS Kinetic.
