### ISSUE TITLE
missing dependencies 

### ISSUE THREAD

**Issue by tkelestemur** [davetcoleman/moveit#6]
Hi, 
After running `rosdep install --from-paths . --ignore-src --rosdistro kinetic` I get this error:
```
ERROR: the following packages/stacks could not have their rosdep keys resolved to system dependencies:
moveit_planners_ompl: Cannot locate rosdep definition for [ompl]
moveit_ros_perception: No definition of [libglew-dev] for OS version [xenial]
moveit_commander: No definition of [python-pyassimp] for OS version [xenial]

```
I have Ubuntu 16.04 with ROS Kinetic. Is this normal or am missing something?

**Comment by davetcoleman** [comment]
See README https://github.com/davetcoleman/moveit#use-shadow-fixed-to-build

**Comment by davetcoleman** [comment]
...and try ``rosdep update``

**Comment by tkelestemur** [comment]
It worked after `rosdep update`. Thanks!
