### ISSUE TITLE
[CI] "fatal Remote branch blacklist_tests not found in upstream origin"

### ISSUE THREAD

**Issue by 130s** [davetcoleman/moveit#8]
https://travis-ci.org/davetcoleman/moveit/builds/147849560
> $ git clone -q https://github.com/ros-planning/moveit_ci.git -b blacklist_tests .moveit_ci
> fatal: Remote branch blacklist_tests not found in upstream origin 
> Unexpected end of command stream
>
> The command "git clone -q https://github.com/ros-planning/moveit_ci.git -b blacklist_tests .moveit_ci" failed and exited with 128 during .

I was navigated to the test result above from your email offline, but is that what you wanted us to look at @davetcoleman ?

**Comment by davetcoleman** [comment]
I see the bug and am fixing it, no prob.

I don't remember when I asked you to look at that link, though - where was that?

**Comment by 130s** [comment]
Ok, I sent an offline msg for the email I mentioned.
